<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpdateSchoolsSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('schools')->truncate();

        $schools = [
            ['school_id' => '126097', 'name' => 'Ayala Central School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303915', 'name' => 'Ayala National High School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126098', 'name' => 'Baluno Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126099', 'name' => 'Cabigan Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126100', 'name' => 'Cawit Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303916', 'name' => 'Ecc-Baluno National High School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126101', 'name' => 'Lima Elementary', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126102', 'name' => 'Maasin Learning Center', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126103', 'name' => 'Recodo Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314805', 'name' => 'Recodo National High School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126104', 'name' => 'Sinunuc Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303932', 'name' => 'Sinunuc National High School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126105', 'name' => 'Sto.Niño Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126097', 'name' => 'Tulungatung Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314807', 'name' => 'Tulungatung National High School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126107', 'name' => 'Zambame Elementary School', 'district_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126108', 'name' => 'Baliwasan Central School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '345869', 'name' => 'Baliwasan Senior High School - Stand Alone', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126109', 'name' => 'Capisan Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314804', 'name' => 'Capisan National High School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126110', 'name' => 'John Spirig Sr. Memorial Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126111', 'name' => 'Malagutay Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126112', 'name' => 'San Jose Gusu Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126113', 'name' => 'Southcom Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303933', 'name' => 'Southcom National High School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126114', 'name' => 'Southern Support Command Elementary School', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303942', 'name' => 'Zamboanga National High School - West', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303942', 'name' => 'Zamboanga National High School West - Rio Hondo Annex', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126136', 'name' => 'Cadalagan Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126137', 'name' => 'Camp Susana Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199007', 'name' => 'Campo Uno Primary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126138', 'name' => 'Datu Panguluhan Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126140', 'name' => 'Labuan Central School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126141', 'name' => 'Latap Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199005', 'name' => 'Latap Elementary School - Lacumba', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126143', 'name' => 'Limpapa Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303927', 'name' => 'Limpapa National High School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126144', 'name' => 'Mt.View Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126145', 'name' => 'Pamucutan Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126146', 'name' => 'Patalon Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126147', 'name' => 'Pole Diutay  Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126139', 'name' => 'Pole Grande Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303924', 'name' => 'Ramon Enriquez High School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126148', 'name' => 'San Ramon Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126149', 'name' => 'Sinubong Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303925', 'name' => 'Sinubong National High School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126150', 'name' => 'Talisayan Elementary School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303935', 'name' => 'Talisayan National High School', 'district_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126211', 'name' => 'Bandera Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126212', 'name' => 'Cabatangan Clementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126221', 'name' => 'Catalina Vda. De Jalon Memorial School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303923', 'name' => 'Don Pablo Lorenzo Memorial High School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '302765', 'name' => 'Don Pablo Lorenzo Memorial High SHS School Stand - Alone', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126213', 'name' => 'Dulian Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126214', 'name' => 'Edwin Andrews Air Base Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126215', 'name' => 'Luyahan Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126216', 'name' => 'Muruk Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126217', 'name' => 'Pasonanca Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314808', 'name' => 'Pasonanca National High School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '394045', 'name' => 'Regional Science High School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126218', 'name' => 'Salum Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126219', 'name' => 'San Roque Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314809', 'name' => 'San Roque National High School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126220', 'name' => 'Sta. Maria Central School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '363368', 'name' => 'Tumaga National High School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126222', 'name' => 'Upper Pasonanca Elementary School', 'district_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '502326', 'name' => 'Canelar Integrated School', 'district_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126208', 'name' => 'Mariki Elementary School', 'district_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126209', 'name' => 'Rio Hondo Elementary School', 'district_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126210', 'name' => 'Sta Barbara Central School', 'district_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199006', 'name' => 'Zamboanga Central School', 'district_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '501887', 'name' => 'Buenavista Integrated School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126117', 'name' => 'Calabasa Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '306482', 'name' => 'Calabasa National High School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126118', 'name' => 'Camp Pilar Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126119', 'name' => 'Cansilayan Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126120', 'name' => 'Cristino M. Paragas Memorial Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303921', 'name' => 'Curuan National High School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303921', 'name' => 'Curuan National High School - Quiniput Annex', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126122', 'name' => 'Dita Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126123', 'name' => 'Latuan Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '306481', 'name' => 'Latuan National High School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126124', 'name' => 'Lubigan Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314802', 'name' => 'Lubigan National High School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '125126', 'name' => 'Marangan Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126126', 'name' => 'Mina Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126127', 'name' => 'Muti Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126128', 'name' => 'Natividad M. Medalle-Presa Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199002', 'name' => 'Niyog-Niyog Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199001', 'name' => 'Panubigan Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '306480', 'name' => 'Sapa Manok Curuan National High School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126130', 'name' => 'Sapa Manok Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126131', 'name' => 'Sapa Moro Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126132', 'name' => 'Sibutat Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126133', 'name' => 'Simanta Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126134', 'name' => 'Upper Masaba Elementary School', 'district_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126151', 'name' => 'Baluno Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126152', 'name' => 'Bolong Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303917', 'name' => 'Bolong National High School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303918', 'name' => 'Bunguaio National High School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126153', 'name' => 'Bunguiao Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126155', 'name' => 'Camp Socorro Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126156', 'name' => 'Don Francisco Ong C. Seng Memorial Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126158', 'name' => 'Eligna Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '305994', 'name' => 'Lamisahan National High School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126163', 'name' => 'Mangga Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126164', 'name' => 'Manicahan Central School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303928', 'name' => 'Manicahan National High School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126125', 'name' => 'Manicahan Poblacion Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126166', 'name' => 'Nangka Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126168', 'name' => 'Pasilmanta Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126169', 'name' => 'Poso Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126170', 'name' => 'Sangali Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303930', 'name' => 'Sangali National High School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126171', 'name' => 'Sapa Seco Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126172', 'name' => 'Shigeru Memorial Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126173', 'name' => 'Siguinan Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126174', 'name' => 'Sinunuk Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126175', 'name' => 'Tumalutab Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126176', 'name' => 'Udjung Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126177', 'name' => 'Victoria Elementary School', 'district_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126145', 'name' => 'Busay Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126179', 'name' => 'Cabaluay Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303919', 'name' => 'Cabaluay National High School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '137108', 'name' => 'Cabaluay Vida Vista', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126180', 'name' => 'Cacao Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126181', 'name' => 'Culianan Learning Center', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303920', 'name' => 'Culianan National High School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126183', 'name' => 'Imelda Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126184', 'name' => 'Islamia Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126160', 'name' => 'Landang Laum Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126185', 'name' => 'Lanote Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126187', 'name' => 'Lapakan Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126188', 'name' => 'Lumbayao Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303929', 'name' => 'Mercedes National High School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126190', 'name' => 'Mulu-Muluan Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126192', 'name' => 'Pangulayan Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126193', 'name' => 'Talabaan Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126194', 'name' => 'Taluksangay Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126195', 'name' => 'Tolosa Elementary School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303937', 'name' => 'Tolosa National High School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '501155', 'name' => 'Tuan Datu Hadji Nuno Memorial Integrated School', 'district_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126196', 'name' => 'Balunu Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126198', 'name' => 'Divisoria Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126199', 'name' => 'Lugakit Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126201', 'name' => 'Lumbangan Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126202', 'name' => 'Lunzuran Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303922', 'name' => 'Maria Clara L. Lobregat National High School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '502255', 'name' => 'Pasobolong Integrated School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126204', 'name' => 'Putik Central School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126205', 'name' => 'Salaan Elementary School', 'district_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126223', 'name' => 'Arena Blanco East Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303914', 'name' => 'Arena Blanco National High School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126224', 'name' => 'Arena Blanco West Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126159', 'name' => 'Landang Gua Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314803', 'name' => 'Landang Gua National High School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126226', 'name' => 'Mampang Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '305996', 'name' => 'Mampang National High School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '501110', 'name' => 'Manalipa Integrated School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126167', 'name' => 'Panganak Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126227', 'name' => 'Pangapuyan Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126228', 'name' => 'Talon-Talon Central School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '314801', 'name' => 'Talon-Talon National High School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126230', 'name' => 'Tigtabon Elementary School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '305995', 'name' => 'Tigtabon National High School', 'district_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199008', 'name' => 'Bihing Tahik Primary School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126207', 'name' => 'Don Gregorio Evangelista Memorial School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126225', 'name' => 'Guiwan Elementary School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126229', 'name' => 'Tetuan Central School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126231', 'name' => 'Tugbungan Elementary School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303940', 'name' => 'Zamboanga City High School', 'district_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303931', 'name' => 'Antonio A. Angeles High School - SNHS', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126233', 'name' => 'Davuy Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126234', 'name' => 'Dr. Manuel S Diaz Memorial Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '502811', 'name' => 'Licomo Integrated School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126236', 'name' => 'Limaong Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303926', 'name' => 'Limaong National High Shool', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126238', 'name' => 'Malanta Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '500244', 'name' => 'Mangusu Integrated School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126240', 'name' => 'Matarling Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199004', 'name' => 'Matiti Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126241', 'name' => 'Merloquet Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126242', 'name' => 'Mulawin Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '306971', 'name' => 'Sibuktok National High School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '199003', 'name' => 'Sibuktok Primary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126244', 'name' => 'Sibulao Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126245', 'name' => 'Sinoropan Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '305645', 'name' => 'Sinoropan National High School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126247', 'name' => 'Tagasilay Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303934', 'name' => 'Tagasilay National High School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126248', 'name' => 'Tagpangi Es/Sta.Fe Annex', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126249', 'name' => 'Taguiti Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126250', 'name' => 'Talaga Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126252', 'name' => 'Tamion Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126253', 'name' => 'Tarlago Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126254', 'name' => 'Tictapul Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303936', 'name' => 'Tictapul National High School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126255', 'name' => 'Tigbalabag Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126256', 'name' => 'Tigui Elementary Schoo﻿l', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126257', 'name' => 'Tindalo Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126258', 'name' => 'Tumitus Elementary School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '126259', 'name' => 'Vitali Central School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303939', 'name' => 'Vitali National High School', 'district_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['school_id' => '303933', 'name' => 'SOUTHCOM NATIONAL HIGH SCHOOL', 'district_id' => 4, 'created_at' => now(), 'updated_at' => now()],
        ];

        foreach (array_chunk($schools, 50) as $chunk) {
            DB::table('schools')->insert($chunk);
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
