import shutil

src = 'resources/views/partials/inventory-edit-step.blade.php'
dst = 'resources/views/partials/building-edit-step.blade.php'
shutil.copy(src, dst)

with open(dst, 'r', encoding='utf-8') as f:
    c = f.read()

replacements = [
    ('stepInventoryEdit','stepBuildingEdit'),
    ('editFilterSection','bldgFilterSection'),
    ('toggleEditFilters','toggleBldgFilters'),
    ('toggleEditFilterBtn','toggleBldgFilterBtn'),
    ('editFilterClass','bldgFilterClass'),
    ('editFilterCat','bldgFilterCat'),
    ('editFilterItem','bldgFilterArticle'),
    ('editFilterSort','bldgFilterSort'),
    ('editFilterSchool','bldgFilterSchool'),
    ('editFilterSource','bldgFilterOccupancy'),
    ('editFilterMode','bldgFilterType'),
    ('editFilterDate','bldgFilterDate'),
    ('editFilterIntegrity','bldgFilterIntegrity'),
    ('clearEditFilters','clearBldgFilters'),
    ('editAssetTableCard','bldgAssetTableCard'),
    ('editAssetToolbar','bldgAssetToolbar'),
    ('editTabAssetSource','bldgTabSource'),
    ('editTabAssetDist','bldgTabDist'),
    ('switchEditAssetTab','switchBldgTab'),
    ('editAssetTabLabel','bldgTabLabel'),
    ('editPanelAssetSource','bldgPanel'),
    ('editPanelAssetDist','bldgPanelDist'),
    ('editSourceScroll','bldgScroll'),
    ('editDistScroll','bldgDistScroll'),
    ('editAssetSourceBody','bldgTableBody'),
    ('editAssetDistBody','bldgDistBody'),
    ('editRowCountLabel','bldgRowCountLabel'),
    ('editPaginationControls','bldgPaginationControls'),
    ('editPrevBtn','bldgPrevBtn'),
    ('editNextBtn','bldgNextBtn'),
    ('editBulkModal','bldgBulkModal'),
    ('editBulkFrom','bldgBulkFrom'),
    ('editBulkTo','bldgBulkTo'),
    ('editUndoBtn','bldgUndoBtn'),
    ('editRedoBtn','bldgRedoBtn'),
    ('openEditBulkModal','openBldgBulkModal'),
    ('closeEditBulkModal','closeBldgBulkModal'),
    ('applyEditBulk','applyBldgBulk'),
    ('saveEditChanges','saveBldgChanges'),
    ('initInventoryEdit','initBldgEdit'),
    ('renderEditTable','renderBldgTable'),
    ('syncEditCell','syncBldgCell'),
    ('updateEditUndoBtn','updateBldgUndoBtn'),
    ('editPrevPage','bldgPrevPage'),
    ('editNextPage','bldgNextPage'),
    ('editFetchData','bldgFetchData'),
    ('editAllData','bldgAllData'),
    ('editOriginalData','bldgOriginalData'),
    ('editUndoStack','bldgUndoStack'),
    ('editRedoStack','bldgRedoStack'),
    ('editCurrentPage','bldgCurrentPageNum'),
    ('editRowsPerPage','bldgRowsPerPage'),
    ('editUndo','bldgUndo'),
    ('editRedo','bldgRedo'),
    # Bulk modal input IDs - prefix eb -> beb
    ('"ebClassification"','"bebClassification"'),
    ('"ebCategory"','"bebCategory"'),
    ('"ebItem"','"bebArticle"'),
    ('"ebDescription"','"bebDescription"'),
    ('"ebUom"','"bebUom"'),
    ('"ebAcqSource"','"bebAcqSource"'),
    ('"ebMode"','"bebMode"'),
    ('"ebPersonnel"','"bebPersonnel"'),
    ('"ebPosition"','"bebPosition"'),
    ('"ebCost"','"bebCost"'),
    ('"ebQty"','"bebQty"'),
    ('"ebLife"','"bebLife"'),
    ('"ebDate1"','"bebDate1"'),
    ('"ebRemarks"','"bebRemarks"'),
    ('"ebSchoolType"','"bebSchoolType"'),
    ('"ebSchoolId"','"bebSchoolId"'),
    ('"ebSchoolName"','"bebSchoolName"'),
    ('"ebOccupancy"','"bebOccupancy"'),
    ('"ebLocation"','"bebLocation"'),
    ('"ebPropertyNo"','"bebPropertyNo"'),
    ('"ebDate2"','"bebDate2"'),
    ("'ebClassification'","'bebClassification'"),
    ("'ebCategory'","'bebCategory'"),
    ("'ebItem'","'bebArticle'"),
    ("'ebDescription'","'bebDescription'"),
    ("'ebUom'","'bebUom'"),
    ("'ebAcqSource'","'bebAcqSource'"),
    ("'ebMode'","'bebMode'"),
    ("'ebPersonnel'","'bebPersonnel'"),
    ("'ebPosition'","'bebPosition'"),
    ("'ebCost'","'bebCost'"),
    ("'ebQty'","'bebQty'"),
    ("'ebLife'","'bebLife'"),
    ("'ebDate1'","'bebDate1'"),
    ("'ebRemarks'","'bebRemarks'"),
    ("'ebSchoolType'","'bebSchoolType'"),
    ("'ebSchoolId'","'bebSchoolId'"),
    ("'ebSchoolName'","'bebSchoolName'"),
    ("'ebOccupancy'","'bebOccupancy'"),
    ("'ebLocation'","'bebLocation'"),
    ("'ebPropertyNo'","'bebPropertyNo'"),
    ("'ebDate2'","'bebDate2'"),
    ('id="ebCostTotal"','id="bebCostTotal"'),
]
for old, new in replacements:
    c = c.replace(old, new)

with open(dst, 'w', encoding='utf-8') as f:
    f.write(c)
print('Step 1 done')
